Fix error handling for clients with no IPs
When the 'ip' key is present, but with no value (None), the
function used to build the description of the client which contains
the issue breaks:

...
  File "/arouteserver/pierky/arouteserver/config/clients.py", line 146, in parse
    client_descr = get_client_descr(client)
  File "/arouteserver/pierky/arouteserver/config/clients.py", line 40, in get_client_descr
    client_descr += " " + client["ip"]
TypeError: can only concatenate str (not "NoneType") to str

Closes #87